### PR TITLE
DE48454 - Fix images loading in Consistent Eval

### PR DESCRIPTION
**Pull request by svanherk**
This looks to be a regression from the migration to Lit. The `token` can be a `string` or a `function`, but the attribute is only handling the `string` case so we need to pass it as a property instead. The better solution may be to update the `token` attribute converter to be smarter around this, but looking to make a more minimal change right before branching.

I believe Quick Eval didn't see the same issue because it uses the `users` route (instead of `enrolled-user`) and seems to have a fallback to a valence route with cookie auth.

### CODE REVIEW

**Review by JamieTran — COMMENTED** [review]
I tried testing this change on my local environment and it didn't seem to fix it in Consistent Eval (I haven't updated my LMS in a couple of days, not sure if that would change anything).

**Review by tdevos-d2l — DISMISSED** [review]
lgtm!

**Comment by tdevos-d2l** [comment]
Ignore my approval until JT approves haha

**Comment by svanherk** [comment]
> I tried testing this change on my local environment and it didn't seem to fix it in Consistent Eval (I haven't updated my LMS in a couple of days, not sure if that would change anything).

Hmm, shouldn't rely on anything in the LMS.  You're hosting a local BSI?  If you put a breakpoint at https://github.com/BrightspaceHypermediaComponents/users/blob/main/components/d2l-profile-image-base.js#L288, what does it say `this.token` is?

**Comment by JamieTran** [comment]
> > I tried testing this change on my local environment and it didn't seem to fix it in Consistent Eval (I haven't updated my LMS in a couple of days, not sure if that would change anything).
> 
> Hmm, shouldn't rely on anything in the LMS. You're hosting a local BSI? If you put a breakpoint at https://github.com/BrightspaceHypermediaComponents/users/blob/main/components/d2l-profile-image-base.js#L288, what does it say `this.token` is?

Yeah, I'm hosting local BSI. This function isn't getting hit. It is exiting on https://github.com/BrightspaceHypermediaComponents/users/blob/main/components/d2l-profile-image-base.js#L280

**Review by JamieTran — APPROVED** [review]
My instance permissions were not set up correctly for user-profiles. This fix works 👍 Sorry for the confusion 😵‍💫

**Review by tdevos-d2l — APPROVED** [review]

**Pull request merged**
